### ISSUE TITLE
Never see a hidden data NFT from NFT page or 'My Collection' page. (Chrome)

### ISSUE THREAD

**Issue by hpzxk** [SecretChainGirl-Foundation/stashh-QA#190] opened 2021-11-28 15:03 UTC
## Steps to reproduce
1. Go to a hidden data NFT page  (e.g: http://stashh.io/asset/secret12txq84gj2zxg6lk9tk8jnsqqqp8veklfqwflfz/1637978373763_2c5dc)
2. Click on 'Buy now'
3. Click 'See Hidden Data' and 'Create Permit'
4. Pop up transaction failed msg but balance deducted.
![image](https://user-images.githubusercontent.com/14306177/143773245-963b94ed-5cb2-4116-9293-6f5503b914b7.png)
5. Check transactions. 
![image](https://user-images.githubusercontent.com/14306177/143773305-0093523c-4f0f-42b7-bcf6-8d185976b369.png)
6. Only no hidden data NFT displayed in My Collection Page.
![image](https://user-images.githubusercontent.com/14306177/143773367-7a46b646-b38d-4bad-aa50-9dd678d2c20d.png)

(secret1c5yvw0e8xpsdswy6hfs9v2zy403jykgm9k65d8, address if needed.)

## Reproducibility
100%

## Issue:
I bought NFT and I can't see it or even own it.

## Expected:
I paid the money and should check it!

**Comment by scarylooking** [comment] 2021-11-28 16:47
Possible duplicate of #176 + the permit visibility UX flow issue?

**Comment by scarylooking** [comment] 2021-11-28 16:49
Possibly related: #188 #179 #186 #183 #191 #190

**Comment by lauraweindorf** [comment] 2021-12-06 21:25
Verified :tada:

**Closed by lauraweindorf** 2021-12-06 21:25 UTC
Labels: investigation
