### ISSUE TITLE
I keep seeing random 'Transaction fail' message

### ISSUE THREAD

**Issue by Glu3** [SecretChainGirl-Foundation/stashh-QA#187] opened 2021-11-28 09:32 UTC
Tested in (Chrome, Safari, Edge, Firefox, etc.): Mac , Chrome

## Steps to reproduce
1. It happens randomly, the red popup on top right shows up that says 'Transaction fail'

## Reproducibility
Can you make the bug happen again if you repeat the steps above?

## Issue:
Describe the issue you encountered. 

## Expected:
Describe what you expected to happen.

**Comment by scarylooking** [comment] 2021-11-28 16:45
Duplicate of 176

**Closed** 2021-11-28 16:45 UTC
Labels: duplicate
